# -*- coding: utf-8 -*-
"""Book_Visual1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCGTpnGrzIre2kXYp-OxnCNMJyWQB6nQ
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
x = [1,2,3,4,5,6]
ydata = [1,2.8,2.1,4.3,3,3.5]
plt.bar(x,ydata)
plt.show()

import numpy as np
x = np.array([1,2,3,4,5,6])
ydata = np.array([1,2.8,2.1,4,3,3.5])
plt.bar(x,ydata) #กราฟแนวตั้ง
plt.show()
plt.barh(x,ydata) #กราฟแนวนอน ให้เติมเป็น barh
plt.show()