# -*- coding: utf-8 -*-
"""Book_Basic_Statistic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t5KHwI_8NGKLmRxDqyegTEko3peePurM
"""

import pandas as pd
datas = [1.2,2.3,3,1.5,4,2.2]
df = pd.Series(datas)
df.mean()
df.min()
df.max()
df.std()

uri = 'stats_freq.xlsx'
cols = ['Name','Age','Buy','Sex','Gender'] #เลือกคอลัมน์
df = pd.read_excel(uri,usecols=cols)
df.Age.mean() #หาค่าเฉลี่ยอายุ
df.describe() #หาค่าสถิติเบื้องต้น ของคอลัมน์ที่เป็นตัวเลข
df.Sex = df.Sex.astype('category') #เปลี่ยนประเภท Sex เป็น Category เพื่อป้องการการคำนวณตัวเลข

import pandas as pd
datas = [1.2,2.3,3,1.5,4,2.2]
df = pd.Series(datas)
df.median() #หาค่า Median
df.sort_values().values #ข้อมูลที่จัดเรียงแล้ว

import pandas as pd
datas = [1.2,2.3,3,1.5,4,2.2,2.4,2.2,2.5]
df = pd.Series(datas)
df.mode() #หาค่าฐานนิยม

import pandas as pd
datas = [1.2,2.3,3,1.5,4,2.2,2.4,2.2,2.5]
df = pd.Series(datas)
df.describe() #หาค่า Quartile
df.quantile([0.25,0.5,0.75]) #หาค่า Quartile

# Commented out IPython magic to ensure Python compatibility.
data = ['M','M','F','M','F','F','M','M','F']
df = pd.Series(data)
df.value_counts() #นับจำนวนแบบ Group by อย่างง่าย
df.count() #นับจำนวนท้งหมด
# %matplotlib inline
df.value_counts().plot.bar(grid=True) #นำข้อมูลที่ได้มา Plot พร้อมเพิ่ม Grid ในกราฟ